# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 501)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(140, 10, 20, 481))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(160, 10, 631, 481))
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setContextMenuPolicy(Qt.NoContextMenu)
        self.stackedWidget.setLayoutDirection(Qt.LeftToRight)
        self.stackedWidget.setAutoFillBackground(False)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.line_5 = QFrame(self.page)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 40, 641, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_10 = QLabel(self.page)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 0, 431, 31))
        font = QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_10.setFont(font)
        self.stackedWidget.addWidget(self.page)
        self.page0 = QWidget()
        self.page0.setObjectName(u"page0")
        self.line_4 = QFrame(self.page0)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 40, 641, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.page0)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 431, 31))
        self.label_4.setFont(font)
        self.widget = QWidget(self.page0)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(310, 60, 321, 131))
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 71, 16))
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 40, 71, 16))
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 70, 71, 16))
        self.show_IP = QLabel(self.widget)
        self.show_IP.setObjectName(u"show_IP")
        self.show_IP.setGeometry(QRect(80, 10, 231, 16))
        self.show_Port = QLabel(self.widget)
        self.show_Port.setObjectName(u"show_Port")
        self.show_Port.setGeometry(QRect(80, 40, 231, 16))
        self.show_token = QLabel(self.widget)
        self.show_token.setObjectName(u"show_token")
        self.show_token.setGeometry(QRect(80, 70, 231, 16))
        self.widget_2 = QWidget(self.page0)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(20, 60, 231, 131))
        self.server_Port = QLineEdit(self.widget_2)
        self.server_Port.setObjectName(u"server_Port")
        self.server_Port.setGeometry(QRect(80, 40, 131, 20))
        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(2, 12, 71, 16))
        self.label_3 = QLabel(self.widget_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(2, 72, 71, 16))
        self.server_IP = QLineEdit(self.widget_2)
        self.server_IP.setObjectName(u"server_IP")
        self.server_IP.setGeometry(QRect(80, 10, 131, 20))
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(2, 42, 71, 16))
        self.server_token = QLineEdit(self.widget_2)
        self.server_token.setObjectName(u"server_token")
        self.server_token.setGeometry(QRect(80, 70, 131, 20))
        self.server_save = QPushButton(self.widget_2)
        self.server_save.setObjectName(u"server_save")
        self.server_save.setGeometry(QRect(10, 100, 201, 24))
        self.server_Port.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.server_token.raise_()
        self.server_save.raise_()
        self.server_IP.raise_()
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.lineEdit = QLineEdit(self.page1)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 110, 113, 20))
        self.line_3 = QFrame(self.page1)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 40, 641, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_5 = QLabel(self.page1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 431, 31))
        self.label_5.setFont(font)
        self.stackedWidget.addWidget(self.page1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.line_6 = QFrame(self.page_2)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(0, 40, 641, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 0, 431, 31))
        self.label_11.setFont(font)
        self.stackedWidget.addWidget(self.page_2)
        self.page2 = QWidget()
        self.page2.setObjectName(u"page2")
        self.line_2 = QFrame(self.page2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 40, 641, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.page2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 0, 431, 31))
        self.label_6.setFont(font)
        self.stackedWidget.addWidget(self.page2)
        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(580, 0, 221, 31))
        self.window_close = QPushButton(self.widget_3)
        self.window_close.setObjectName(u"window_close")
        self.window_close.setGeometry(QRect(180, 0, 41, 21))
        self.window_close.setContextMenuPolicy(Qt.NoContextMenu)
        self.window_mini = QPushButton(self.widget_3)
        self.window_mini.setObjectName(u"window_mini")
        self.window_mini.setGeometry(QRect(140, 0, 41, 21))
        font1 = QFont()
        font1.setPointSize(9)
        self.window_mini.setFont(font1)
        self.window_mini.raise_()
        self.window_close.raise_()
        self.page_main = QPushButton(self.centralwidget)
        self.page_main.setObjectName(u"page_main")
        self.page_main.setGeometry(QRect(0, 70, 131, 41))
        font2 = QFont()
        font2.setPointSize(10)
        self.page_main.setFont(font2)
        self.page_server = QPushButton(self.centralwidget)
        self.page_server.setObjectName(u"page_server")
        self.page_server.setGeometry(QRect(0, 110, 131, 41))
        self.page_server.setFont(font2)
        self.version = QLabel(self.centralwidget)
        self.version.setObjectName(u"version")
        self.version.setGeometry(QRect(80, 40, 51, 16))
        self.page_other = QPushButton(self.centralwidget)
        self.page_other.setObjectName(u"page_other")
        self.page_other.setGeometry(QRect(0, 190, 131, 41))
        self.page_other.setFont(font2)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 71, 51))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setPointSize(26)
        font3.setBold(True)
        self.label_12.setFont(font3)
        self.label_12.setTextFormat(Qt.PlainText)
        self.label_12.setWordWrap(False)
        self.page_link = QPushButton(self.centralwidget)
        self.page_link.setObjectName(u"page_link")
        self.page_link.setGeometry(QRect(0, 150, 131, 41))
        self.page_link.setFont(font2)
        self.page_tags = QPushButton(self.centralwidget)
        self.page_tags.setObjectName(u"page_tags")
        self.page_tags.setGeometry(QRect(0, 230, 131, 41))
        self.page_tags.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Frp\u5feb\u901f\u914d\u7f6e", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u9875", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5730\u5740", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5730\u5740", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u7aef\u53e3", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5bc6\u94a5", None))
        self.show_IP.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u914d\u7f6e", None))
        self.show_Port.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u914d\u7f6e", None))
        self.show_token.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u914d\u7f6e", None))
        self.server_Port.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u7aef\u53e3\u53f7", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5730\u5740", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5bc6\u94a5", None))
        self.server_IP.setText("")
        self.server_IP.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8f93\u5165IP", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u7aef\u53e3", None))
        self.server_token.setPlaceholderText(QCoreApplication.translate("MainWindow", u"token", None))
        self.server_save.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u94fe\u63a5", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u94fe\u63a5", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u5176\u4ed6\u914d\u7f6e", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.window_close.setText("")
        self.window_mini.setText("")
        self.page_main.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u9875", None))
        self.page_server.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668", None))
        self.version.setText(QCoreApplication.translate("MainWindow", u"v0.0.0", None))
        self.page_other.setText(QCoreApplication.translate("MainWindow", u"\u5176\u4ed6\u914d\u7f6e", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"FSE", None))
        self.page_link.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u94fe\u63a5", None))
        self.page_tags.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
    # retranslateUi

