# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widge_left = QWidget(self.centralwidget)
        self.widge_left.setObjectName(u"widge_left")
        self.widge_left.setGeometry(QRect(10, 10, 131, 481))
        self.page_link = QPushButton(self.widge_left)
        self.page_link.setObjectName(u"page_link")
        self.page_link.setGeometry(QRect(0, 30, 121, 24))
        self.page_server = QPushButton(self.widge_left)
        self.page_server.setObjectName(u"page_server")
        self.page_server.setGeometry(QRect(0, 0, 121, 24))
        self.window_close = QPushButton(self.widge_left)
        self.window_close.setObjectName(u"window_close")
        self.window_close.setGeometry(QRect(0, 420, 121, 24))
        self.window_mini = QPushButton(self.widge_left)
        self.window_mini.setObjectName(u"window_mini")
        self.window_mini.setGeometry(QRect(0, 450, 121, 24))
        self.page_other = QPushButton(self.widge_left)
        self.page_other.setObjectName(u"page_other")
        self.page_other.setGeometry(QRect(0, 60, 121, 24))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(140, 10, 20, 481))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(160, 10, 631, 481))
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setContextMenuPolicy(Qt.NoContextMenu)
        self.stackedWidget.setLayoutDirection(Qt.LeftToRight)
        self.stackedWidget.setAutoFillBackground(False)
        self.page0 = QWidget()
        self.page0.setObjectName(u"page0")
        self.line_4 = QFrame(self.page0)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 40, 641, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.page0)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 431, 31))
        font = QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_4.setFont(font)
        self.widget = QWidget(self.page0)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(310, 60, 321, 131))
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 71, 16))
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 40, 71, 16))
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 70, 71, 16))
        self.show_IP = QLabel(self.widget)
        self.show_IP.setObjectName(u"show_IP")
        self.show_IP.setGeometry(QRect(80, 10, 231, 16))
        self.show_Port = QLabel(self.widget)
        self.show_Port.setObjectName(u"show_Port")
        self.show_Port.setGeometry(QRect(80, 40, 231, 16))
        self.show_token = QLabel(self.widget)
        self.show_token.setObjectName(u"show_token")
        self.show_token.setGeometry(QRect(80, 70, 231, 16))
        self.widget_2 = QWidget(self.page0)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(20, 60, 231, 131))
        self.server_Port = QLineEdit(self.widget_2)
        self.server_Port.setObjectName(u"server_Port")
        self.server_Port.setGeometry(QRect(80, 40, 131, 20))
        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(2, 12, 71, 16))
        self.label_3 = QLabel(self.widget_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(2, 72, 71, 16))
        self.server_IP = QLineEdit(self.widget_2)
        self.server_IP.setObjectName(u"server_IP")
        self.server_IP.setGeometry(QRect(80, 10, 131, 20))
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(2, 42, 71, 16))
        self.server_token = QLineEdit(self.widget_2)
        self.server_token.setObjectName(u"server_token")
        self.server_token.setGeometry(QRect(80, 70, 131, 20))
        self.server_save = QPushButton(self.widget_2)
        self.server_save.setObjectName(u"server_save")
        self.server_save.setGeometry(QRect(10, 100, 201, 24))
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.lineEdit = QLineEdit(self.page1)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 110, 113, 20))
        self.line_3 = QFrame(self.page1)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 40, 641, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_5 = QLabel(self.page1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 431, 31))
        self.label_5.setFont(font)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QWidget()
        self.page2.setObjectName(u"page2")
        self.line_2 = QFrame(self.page2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 40, 641, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.page2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 0, 431, 31))
        self.label_6.setFont(font)
        self.stackedWidget.addWidget(self.page2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Frp\u5feb\u901f\u914d\u7f6e", None))
        self.page_link.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u94fe\u63a5", None))
        self.page_server.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5730\u5740", None))
        self.window_close.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.window_mini.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0f\u5316", None))
        self.page_other.setText(QCoreApplication.translate("MainWindow", u"\u5176\u4ed6\u914d\u7f6e", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5730\u5740", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5730\u5740", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u7aef\u53e3", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5bc6\u94a5", None))
        self.show_IP.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u914d\u7f6e", None))
        self.show_Port.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u914d\u7f6e", None))
        self.show_token.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u914d\u7f6e", None))
        self.server_Port.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1024-65535", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5730\u5740", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u5bc6\u94a5", None))
        self.server_IP.setPlaceholderText(QCoreApplication.translate("MainWindow", u"127.0.0.1", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u7aef\u53e3", None))
        self.server_token.setPlaceholderText(QCoreApplication.translate("MainWindow", u"token", None))
        self.server_save.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u94fe\u63a5", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u94fe\u63a5", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5176\u4ed6\u914d\u7f6e", None))
    # retranslateUi

